Topic modeling allows us to efficiently analyze large volumes of texts by clustering documents together into topics.

A large amount of text data is actually unlabeled, meaning we won't be able to apply
our previous supervised learning approaches because those machine learning models would actually depend on historical label data.

Latent Dirichlet Allocation (LDA) with Python

In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv("npr.csv")
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [3]:
# npr['Article'][4000]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [4]:
len(npr)

11992

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
cv = CountVectorizer(max_df=0.9,
                     min_df=2,
                     stop_words='english')

In [9]:
dtm = cv.fit_transform(npr["Article"])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

In [11]:
LDA = LatentDirichletAllocation(n_components=7, 
                                random_state=42)

In [14]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [16]:
# Grab the vocabulary of words
len(cv.get_feature_names_out())

54777

In [17]:
type(cv.get_feature_names_out())

numpy.ndarray

In [19]:
cv.get_feature_names_out()[15000]

'dominican'

In [20]:
import random

In [23]:
random_word_id = random.randint(0, len(cv.get_feature_names_out()))
print(random_word_id)
                                
cv.get_feature_names_out()[random_word_id]

23935


'hurling'

In [ ]:
# Grab the topics

In [24]:
len(LDA.components_)

7

In [25]:
type(LDA.components_)

numpy.ndarray

In [26]:
LDA.components_.shape

(7, 54777)

In [28]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [29]:
# Getting index location for high probability words
single_topic = LDA.components_[0]
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [30]:
import numpy as np

arr = np.array([10,200,1])
arr

array([ 10, 200,   1])

In [31]:
arr.argsort()

array([2, 0, 1], dtype=int64)

In [33]:
# ARGSOFT ---> INDEX POSITIONS SORTED FROM LEAST ---> GREATEST

# TOP 10 VALUES (10 GREATEST VALUES)
# LAST 10 VALUES of ARGSOFT()
single_topic.argsort()[-10:]    # grab the 10 values of .argsoft()

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [37]:
top_20_words = single_topic.argsort()[-20:]

In [38]:
for index in top_20_words:
    print(cv.get_feature_names_out()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [ ]:
# Grab the highest proability words per topic

In [40]:
for i,topic in enumerate(LDA.components_):
    print(f"The top 15 words for topic {i}")
    print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print("\n")
    print("\n")

The top 15 words for topic 0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




The top 15 words for topic 1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




The top 15 words for topic 2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




The top 15 words for topic 3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




The top 15 words for topic 4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




The top 15 words for topic 5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'thi

In [41]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [42]:
npr

Article
0      In the Washington of 2016, even when the polic...
1        Donald Trump has used Twitter  —   his prefe...
2        Donald Trump is unabashedly praising Russian...
3      Updated at 2:50 p. m. ET, Russian President Vl...
4      From photography, illustration and video, to d...
...                                                  ...
11987  The number of law enforcement officers shot an...
11988    Trump is busy these days with victory tours,...
11989  It’s always interesting for the Goats and Soda...
11990  The election of Donald Trump was a surprise to...
11991  Voters in the English city of Sunderland did s...

[11992 rows x 1 columns]

In [43]:
# create a list of the actual topics off this document term matrix.
topic_results = LDA.transform(dtm)

In [45]:
# Probability of a topic belonging to a doc
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [46]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [44]:
topic_results.shape

(11992, 7)

In [47]:
topic_results[0].argmax()

1

In [48]:
# argmax returns back the index position of the highest probability.
npr['Topic'] = topic_results.argmax(axis=1)
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]

LDA is a probabilistic model and NMF is a matrix factorization and multivariate analysis technique.

Non-negative Matrix Factorization: Non-negative matrix factorization is an unsupervised algorithm that simultaneously performs dimensionality reduction and clustering.

Because of LDA's dependence on per-word-count probabilities with the Dirichlet probability distribution,
we could only use count vectorizers for LDA.

But since non-negative matrix factorization works of coefficient values, here, we can actually pre-process the text
with TF-IDF vectorization.

In [49]:
import pandas as pd
npr = pd.read_csv("npr.csv")

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

keep in mind, TF-IDF vectorizer actually performs a count vectorizer beforehand.

In [53]:
tfidf = TfidfVectorizer(max_df=0.95,
                        min_df=2,
                        stop_words="english")

In [54]:
# document term matrix
dtm = tfidf.fit_transform(npr['Article'])
dtm

<11992x54777 sparse matrix of type '<class 'numpy.float64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

In [55]:
from sklearn.decomposition import NMF

In [56]:
# Non-Negative Matrix Factorization (NMF)
nmf_model = NMF(n_components=7, random_state=42)

In [57]:
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

notice is NMF performs faster than LDA for this particular data set.

because of the way NumPy works

In [58]:
tfidf.get_feature_names_out()[2300]

'albala'

In [60]:
for index,topic in enumerate(nmf_model.components_):
    print(f"The Top 15 words for topic # {index}")
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print("\n")

The Top 15 words for topic # 0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


The Top 15 words for topic # 1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


The Top 15 words for topic # 2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


The Top 15 words for topic # 3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


The Top 15 words for topic # 4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


The Top 15 words for topic # 5
['love', 've', 'don

In [64]:
topic_results = nmf_model.transform(dtm)
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3], dtype=int64)

In [65]:
npr['Topic'] = topic_results.argmax(axis=1)
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      3
4  From photography, illustration and video, to d...      6

In [69]:
sorted(npr['Topic'].unique())

[0, 1, 2, 3, 4, 5, 6]

In [70]:
mytopic_dict = {0:"Health", 1:"election", 2:"legis", 3:"poli", 4:"election", 5:"music", 6:"edu"}
npr["Topic Label"] = npr["Topic"].map(mytopic_dict)
npr.head()

Article  Topic Topic Label
0  In the Washington of 2016, even when the polic...      1    election
1    Donald Trump has used Twitter  —   his prefe...      1    election
2    Donald Trump is unabashedly praising Russian...      1    election
3  Updated at 2:50 p. m. ET, Russian President Vl...      3        poli
4  From photography, illustration and video, to d...      6         edu

LDA is a probabilistic model and NMF is a matrix factorization and multivariate analysis technique.