3 or more hidden layers is "deep network"

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils._bunch.Bunch

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [10]:
X = iris.data
# X

In [9]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# One hot encoding y
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

from keras.utils import to_categorical

y = to_categorical(y)
y.shape

(150, 3)

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [13]:
# for neural networks, it's usually a really good idea to scale or standardized your data.

from sklearn.preprocessing import MinMaxScaler

In [14]:
np.array([5, 10, 15, 20])/20

array([0.25, 0.5 , 0.75, 1.  ])

In [15]:
scaler_obj = MinMaxScaler()

In [16]:
scaler_obj.fit(X_train)

scaled_X_train = scaler_obj.transform(X_train)
scaled_X_test = scaler_obj.transform(X_test)

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [19]:
model = Sequential()
# Input Layer
model.add(Dense(units=8, input_dim=4, activation="relu"))
model.add(Dense(units=8, input_dim=4, activation="relu"))

# output layer
model.add(Dense(3, activation="softmax"))   # [0.2, 0.3, 0.5]

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(scaled_X_train, y_train, epochs=150,verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.0986 - accuracy: 0.3100 - 919ms/epoch - 230ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0934 - accuracy: 0.3100 - 8ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0881 - accuracy: 0.3100 - 11ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0837 - accuracy: 0.3200 - 14ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0794 - accuracy: 0.3400 - 10ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0756 - accuracy: 0.4100 - 20ms/epoch - 5ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0718 - accuracy: 0.4900 - 23ms/epoch - 6ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0684 - accuracy: 0.5500 - 17ms/epoch - 4ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0649 - accuracy: 0.6200 - 17ms/epoch - 4ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0618 - accuracy: 0.6300 - 25ms/epoch - 6ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0585 - accuracy: 0.6300 - 17ms/epoch - 4ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0552 - accuracy: 0.6300 - 17ms/epoch - 4ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0521 - accuracy

In [22]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [23]:
model.predict(scaled_X_test)

2/2 [==============================] - 0s 20ms/step


array([[2.75872480e-02, 5.75949848e-01, 3.96462947e-01],
       [9.73631680e-01, 2.20070463e-02, 4.36131563e-03],
       [3.72945127e-04, 1.15000896e-01, 8.84626150e-01],
       [2.13076230e-02, 5.37413955e-01, 4.41278487e-01],
       [1.69758406e-02, 4.68924046e-01, 5.14100134e-01],
       [9.50397253e-01, 4.06350493e-02, 8.96776840e-03],
       [8.26227963e-02, 5.99038064e-01, 3.18339169e-01],
       [2.76060891e-03, 2.61841476e-01, 7.35397935e-01],
       [8.59618280e-03, 3.42262447e-01, 6.49141312e-01],
       [5.24710566e-02, 5.94900131e-01, 3.52628857e-01],
       [6.34773634e-03, 3.90137166e-01, 6.03515089e-01],
       [9.25636947e-01, 5.94925061e-02, 1.48705794e-02],
       [9.67518926e-01, 2.68038288e-02, 5.67724183e-03],
       [9.36018467e-01, 5.15278503e-02, 1.24536371e-02],
       [9.75723028e-01, 2.04065498e-02, 3.87042388e-03],
       [2.41958238e-02, 5.76368690e-01, 3.99435431e-01],
       [1.49228645e-03, 2.38321096e-01, 7.60186553e-01],
       [4.96069193e-02, 5.92913

In [27]:
# model.predict_classes(scaled_X_test)
predict_x=model.predict(scaled_X_test)
class_predictions=np.argmax(predict_x,axis=1)
class_predictions

2/2 [==============================] - 0s 12ms/step


array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [28]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [29]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [30]:
print(confusion_matrix(y_test.argmax(axis=1), class_predictions))
print(classification_report(y_test.argmax(axis=1), class_predictions))
print(accuracy_score(y_test.argmax(axis=1), class_predictions))


[[19  0  0]
 [ 0 13  2]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

0.96


# Save and loading a model

In [31]:
model.save("first_model.h5")

In [32]:
from keras.models import load_model

In [33]:
new_model = load_model("first_model.h5")

In [34]:
predict_x=model.predict(scaled_X_test)
class_predictions_new=np.argmax(predict_x,axis=1)
class_predictions_new

2/2 [==============================] - 0s 3ms/step


array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

Recurrent Neural Network

Recurrent neural networks are specifically designed to work with sequence data.

So examples of sequence data are things like time series data, such as how many sales have happened
over a previous time series or what the production has been over a previous time series.

There's also things like sentences, which is what we're focusing on for natural language processing. So you can think of a sentence as just a sequence of words.

Things like audio or music. It's basically just a sequence of sounds or even things like car trajectories.
It's just a sequence of instructions; Left, right, forward, and back.

Cells that are a function of inputs from previous time steps are also known as **memory cells**

RNN are also flexible in their inputs and outputs.

Eg: 
- Sequence to Sequence:  we can actually perform a sequence input to a sequence output. And an example of that would be passing in a set of time series information, such as a year's worth of daily sales data. And then wanting back a sequence of that same sales data shifted over a certain time period into the future.

- Sequence to vector: set of examples, inputs and outputs, would be to pass in a sequence input and request back a vector output. a common example of using recurring neural networks for this sort of input and output is sentiment scores. So you can feed in a sequence of words, maybe a paragraph of a movie review, and then request back a vector, indicating whether it was a positive sentiment such as, they really like the movie.So that's usually indicated by one versus they really dislike the movie, which is indicated by usually negative one or zero.

    So on the opposite side, you could also feed in a vector input. So a single input at just a first time step
        and basically pass in zeros for the rest of your time steps. And then let the output be a sequence. **vector to sequence network**... So an example of vector to sequence could be just providing a single seed word and then getting out an entire sequence of high-probability sequence phrases that would actually come out. So you could have a word such as "Hello" and then the sequence that gets generated something like, "How are you?" Because after being trained on lots of introductory text, maybe the neural network realizes that just based off the seed, "Hello," one of the more common phrases is, "How are you?"

LSTMs, GRU, and Text Generation

# LSTM - Long Short Term Memory Units

are going to be necessary in order to actually generate text that makes sense because we wanna have the network be aware of not just the most recent text it's seen, but also the entire history of text that it's seen.



So a common issue that recurrent neural networks face is that after a while, especially if you're training the network on a really large sequence, then the recurrent neural network is going to begin to forget those very first inputs. The later and later training batches of later inputs, things that come towards the end of the text document, that's gonna start kind of overriding the weights of the very beginning inputs
of the beginning of the text. So what we wanna make sure is that we're not beginning to forget those first inputs as information is lost at each step going through the recurrent neural network. So what we really need is we need some sort of long term memory for our networks. We need to balance both the short term memory of the networks, the data that it was recently trained on, versus the long term memory of the networks, all the data and the very first data that was being trained on. So the LSTM, or long short-term memory cell, was created to help address these recurrent neural network issues.

Variants on an LSTM cell

- There's a variant called the peep hole variance. this is actually quite popular, and the reason for that is because it adds peepholes to all the gates.

- **GRU** - Gated Recurrent Unit.  What this ends up doing is it actually simplifies things a bit by combining the forget and input gates into a single, what they call, update gates. And it also merges the cell state and hidden state, and it makes a few other changes. So this resulting model is actually simpler than standard LSTM models.


Depth Gated Recurrent Neural Networks, and that was introduced in 2015.

for text generation LSTMs work best.

Text Generation with LSTMs with Keras and Python

In [36]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()

    return str_text

In [38]:
# read_file("moby_dick_four_chapters.txt")

In [42]:
# Complete Text for book
# read_file("melville-moby_dick.txt")

In [39]:
import spacy

In [41]:
# we can disable certain processes if we want. Below we are only doing tokenization and disabling other processes
nlp = spacy.load("en_core_web_lg", disable=["parser","tagger","ner"])

In [43]:
len(read_file("melville-moby_dick.txt"))

1198622

In [ ]:
nlp.max_length = 1198623

'\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n '

In [44]:
def seperate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [45]:
d = read_file("moby_dick_four_chapters.txt")

In [46]:
tokens = seperate_punc(d)
tokens

c:\Users\manor\OneDrive - kettering.edu\Online Learning Portal Docs\Udemy\Personal\NLP - Natural Language Processing with Python\nlp_venv\lib\site-packages\spacy\pipeline\lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such',
 'an',
 'upper',
 'hand',
 '

In [47]:
len(tokens)

11338

In [48]:
# Pass in 25 words ----> have netword predict 26th word

In [49]:
training_len = 25 + 1 

text_sequence = []

for i in range(training_len, len(tokens)):
    seq = tokens[i-training_len:i]

    text_sequence.append(seq)

print(type(text_sequence))

<class 'list'>


In [52]:
" ".join(text_sequence[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [53]:
#  the next sequence is essentially one word over or one token over.
" ".join(text_sequence[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [54]:
" ".join(text_sequence[2])

'ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i'

In [55]:
from keras.preprocessing.text import Tokenizer

In [56]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequence)

In [61]:
sequences = tokenizer.texts_to_sequences(text_sequence)


In [64]:
# sequences[0]

[956,
 14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 314,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2713,
 14,
 24]

In [65]:
# sequences[1]

[14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 314,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2713,
 14,
 24,
 957]

In [66]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'at',
 18: 'this',
 19: 'you',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'on',
 25: 'be',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'about',
 38: 'no',
 39: 'into',
 40: 'by',
 41: 'were',
 42: 'out',
 43: 'or',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'have',
 48: 'an',
 49: 'upon',
 50: 'little',
 51: 'some',
 52: 'old',
 53: 'like',
 54: 'if',
 55: 'they',
 56: 'would',
 57: 'do',
 58: 'over',
 59: 'landlord',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: "n't",
 65: 'night',
 66: 'here',
 67: 'head',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'time',
 74: 'other',
 75: 'very',
 76: 'go',
 77: 'these',
 78: 'more',
 79: 'though',
 80: 'first',
 81: 'sort',


In [67]:
for i in sequences[0]:
    print(f"{i}: {tokenizer.index_word[i]}")

956: call
14: me
263: ishmael
51: some
261: years
408: ago
87: never
219: mind
129: how
111: long
954: precisely
260: having
50: little
43: or
38: no
314: money
7: in
23: my
546: purse
3: and
150: nothing
259: particular
6: to
2713: interest
14: me
24: on


In [70]:
# for seq in range(len(sequences)):
#     for i in sequences[seq]:
#         print(f"{i}: {tokenizer.index_word[i]}")

In [71]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1003),
             ('money', 120),
             ('in', 5647),
             ('my', 1786),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7150),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 416),
             ('the', 15540),
             ('watery', 26),
  

In [72]:
print(type(tokenizer.word_counts))

<class 'collections.OrderedDict'>


In [83]:
collections = tokenizer.word_counts

In [88]:
items_collections = list(collections.items())
items_collections[:10]

[('call', 27),
 ('me', 2471),
 ('ishmael', 133),
 ('some', 758),
 ('years', 135),
 ('ago', 84),
 ('never', 449),
 ('mind', 164),
 ('how', 321),
 ('long', 374)]

In [90]:
items_collections[0][1]

27

In [91]:
items_collections[0][0]

'call'

In [ ]:
collections = tokenizer.word_counts
# for word, count in range(0, len(list(collections.items()))):
#     word = items_collections[0][0]
#     count = items_collections[0][1]

In [97]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

2718

In [98]:
type(sequences)

list

In [99]:
import numpy as np

In [100]:
sequences = np.array(sequences)
sequences

array([[ 956,   14,  263, ..., 2713,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2712, ...,   53,    2, 2718],
       [ 166, 2712,    3, ...,    2, 2718,   26]])

Build and Train LSTM model

In [101]:
from keras.utils import to_categorical

In [102]:
X = sequences[:,:-1]
# all rows and last col
y = sequences[:,-1]

In [103]:
y = to_categorical(y, num_classes=vocabulary_size+1)

In [104]:
seq_len = X.shape[1]

In [165]:
seq_len

25

In [105]:
X.shape

(11312, 25)

In [119]:
import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding

In [120]:
vocabulary_size

2718

In [166]:
def create_model(vocabulary_size, seq_len):

    model = Sequential()
    # Turns positive integers (indexes) into dense vectors of fixed size.
    model.add(Embedding(vocabulary_size,
                        seq_len,
                        input_length=seq_len))
    # LSTM units to actually be trained on the sequence.
    model.add(LSTM(units=seq_len*2,
                   return_sequences=True))
    model.add(LSTM(50))
    model.add(Dense(50, activation="relu"))
    
    # translate this into a vocabulary word because it's just going to spit out a number.
    model.add(Dense(vocabulary_size, activation="softmax"))

    model.compile(loss="categorical_crossentropy",
                  optimizer="adam",
                  metrics=['accuracy'])
    
    model.summary()

    return model

because of the way the embedding works with padding
for pad sequences, we actually need to add one more space
to essentially hold a zero.

In [167]:
create_model(vocabulary_size+1, seq_len=seq_len)

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 25, 25)            67975     
                                                                 
 lstm_8 (LSTM)               (None, 25, 50)            15200     
                                                                 
 lstm_9 (LSTM)               (None, 50)                20200     
                                                                 
 dense_11 (Dense)            (None, 50)                2550      
                                                                 
 dense_12 (Dense)            (None, 2719)              138669    
                                                                 
Total params: 244,594
Trainable params: 244,594
Non-trainable params: 0
_________________________________________________________________


In [168]:
from pickle import dump,load

In [169]:
import tensorflow as tf

In [ ]:
model.fit(X,y,batch_size=128, epochs=2, verbose=1)

In [ ]:
# save the model to file
model.save('my_mobydick_model.h5')
# save the tokenizer
dump(tokenizer, open('my_mobydick_tokenizer', 'wb'))

# Generating New Text

In [ ]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [ ]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

### Grab a random seed sequence

In [ ]:
sequences[0]

In [ ]:
import random
random.seed(101)
random_pick = random.randint(0,len(sequences))

In [ ]:
random_seed_text = sequences[random_pick]

In [ ]:
random_seed_text

In [ ]:
seed_text = ' '.join(random_seed_text)

In [ ]:
seed_text

In [ ]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=50)

### Exploring Generated Sequence

In [ ]:
full_text = read_file('moby_dick_four_chapters.txt')

In [ ]:
for i,word in enumerate(full_text.split()):
    if word == 'inkling':
        print(' '.join(full_text.split()[i-20:i+20]))
        print('\n')